version = 1
SPDX-PackageName = "kaichat"
SPDX-PackageSupplier = "Laurent Montel <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/utilities/kaichat"

[[annotations]]
path = [".flatpak-manifest.json", "src/widgets/needupdateversion/autotests/data/*.html", "doc/**", "REUSE.toml", "src/widgets/icons/**", "logo.png", "logo.svg", ".gersemirc", "src/plugins/text/sharetext/kaichat_sharetextplugin.json", "src/plugins/text/webshortcut/kaichat_webshortcuttextplugin.json", "src/plugins/tools/currentdatetime/textautogeneratetext_currentdatetimeplugin.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["po/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "LGPL-2.0-or-later"
